"""add column certificate in test answer

Revision ID: 6cc6d1184414
Revises: d12ca93c4a7d
Create Date: 2024-05-12 23:57:10.731182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc6d1184414'
down_revision: Union[str, None] = 'd12ca93c4a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_answers', sa.Column('certificate', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_answers', 'certificate')
    # ### end Alembic commands ###
