"""test answers

Revision ID: d12ca93c4a7d
Revises: ec2023c6c6e9
Create Date: 2024-05-09 00:35:05.517620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12ca93c4a7d'
down_revision: Union[str, None] = 'ec2023c6c6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_answers', sa.Column('total_marks', sa.Integer(), nullable=False))
    op.add_column('test_answers', sa.Column('question_attend', sa.Integer(), nullable=False))
    op.add_column('test_answers', sa.Column('total_question', sa.Integer(), nullable=False))
    op.add_column('test_answers', sa.Column('time_taken', sa.Integer(), nullable=False))
    op.add_column('test_answers', sa.Column('payload', sa.Text(), nullable=False))
    op.drop_column('test_answers', 'is_correct')
    op.drop_column('test_answers', 'question_id')
    op.drop_column('test_answers', 'answer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_answers', sa.Column('answer_id', sa.INTEGER(), nullable=False))
    op.add_column('test_answers', sa.Column('question_id', sa.INTEGER(), nullable=False))
    op.add_column('test_answers', sa.Column('is_correct', sa.INTEGER(), nullable=False))
    op.drop_column('test_answers', 'payload')
    op.drop_column('test_answers', 'time_taken')
    op.drop_column('test_answers', 'total_question')
    op.drop_column('test_answers', 'question_attend')
    op.drop_column('test_answers', 'total_marks')
    # ### end Alembic commands ###
